http:
  routers:
    scribe-router:
      rule: "HostRegexp(`.*`)"
      entryPoints:
        - web
      service: scribe-service
      priority: 10

  services:
    scribe-service:
      loadBalancer:
        servers:
          - url: "http://scribe:8000"
  
  middlewares:
    auth:
      basicAuth:
        users: []  # Add users here for Traefik dashboard protection if needed